title: Hernan Figueroa
description: >- # this means to ignore newlines until "baseurl:"
  This is the public business card for Hernan Figueroa.
baseurl: "" # Site at root
github_username:  hpfigueroa

# Build settings
theme: minima
list_title: A journey