title: Hernan Figueroa
description: >- # this means to ignore newlines until "baseurl:"
  This is the public business card for Hernan Figueroa.
baseurl: "" # the subpath of your site, e.g. /blog
github_username:  hpfigueroa

# Build settings
theme: minima
